require('dotenv').config();
const bcrypt = require('bcryptjs');
const { sequelize, user, tile } = require('./db');

const seedDatabase = async () => {
  try {
    // Sync the database
    console.log('Syncing database...');
    await sequelize.sync({ alter: true });
    console.log('Database synced successfully.');

    // Seed admin user if it doesn't exist
    console.log('Checking for admin user...');
    const adminExists = await user.findOne({ where: { username: 'admin' } });
    if (!adminExists) {
      const hashedPassword = await bcrypt.hash('adminpassword', 10);
      await user.create({
        username: 'admin',
        password: hashedPassword,
        email: 'hgwarner1307@gmail.com',
        role: 'admin',
        subscription: 'pro',
      });
      console.log('Admin user seeded successfully.');
    } else {
      console.log('Admin user already exists, skipping seeding.');
    }

    // Seed tiles if they don't exist
    console.log('Checking for tiles...');
    const existingTiles = await tile.findAll();
    if (existingTiles.length === 0) {
      console.log('Seeding tiles...');
      await tile.bulkCreate([
        {
          name: '500x250 Slate 75mm',
          type: 'slate',
          length: 500,
          width: 250,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 195,
          maxgauge: 210,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 367,
        },
        {
          name: 'CUPA 12 Spanish Slate 500x250',
          type: 'slate',
          length: 500,
          width: 250,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 200,
          maxgauge: 225,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Welsh Slate 400x250',
          type: 'slate',
          length: 400,
          width: 250,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 150,
          maxgauge: 175,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Welsh Slate 300x200',
          type: 'slate',
          length: 300,
          width: 200,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 100,
          maxgauge: 125,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Welsh Penrhyn Capital Grade Slate 500x300',
          type: 'slate',
          length: 500,
          width: 300,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 200,
          maxgauge: 225,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'CUPA 5 Spanish Slate',
          type: 'slate',
          length: 500,
          width: 250,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 200,
          maxgauge: 225,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Delabole Slate',
          type: 'slate',
          length: 500,
          width: 250,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 200,
          maxgauge: 225,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Ffestiniog Blue Grey Slate',
          type: 'slate',
          length: 500,
          width: 300,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 200,
          maxgauge: 225,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Westmorland Green Slate',
          type: 'slate',
          length: 500,
          width: 300,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 200,
          maxgauge: 225,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Marley Birkdale 600x300',
          type: 'fibre-cement-slate',
          length: 600,
          width: 300,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 255,
          maxgauge: 275,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Cembrit Jutland 600x300',
          type: 'fibre-cement-slate',
          length: 600,
          width: 300,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 255,
          maxgauge: 275,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'SVK Ardonit 600x300',
          type: 'fibre-cement-slate',
          length: 600,
          width: 300,
          eave_tile_length: 0,
          headlap: 90,
          crossbonded: 'YES',
          mingauge: 255,
          maxgauge: 275,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Redland 49',
          type: 'interlocking-tile',
          length: 382,
          width: 200,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 343,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Marley Modern',
          type: 'interlocking-tile',
          length: 420,
          width: 292,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'YES',
          mingauge: 293,
          maxgauge: 343,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Redland Regent',
          type: 'interlocking-tile',
          length: 418,
          width: 300,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 343,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Redland Mini Stonewold',
          type: 'interlocking-tile',
          length: 418,
          width: 294,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 293,
          maxgauge: 343,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 334,
        },
        {
          name: 'Marley Mendip',
          type: 'interlocking-tile',
          length: 420,
          width: 298,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 343,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 333,
        },
        {
          name: 'Marley Mendip 12.5 Low Pitch',
          type: 'interlocking-tile',
          length: 420,
          width: 298,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 320,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Sandtoft Double Pantile',
          type: 'interlocking-tile',
          length: 420,
          width: 300,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 100,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Marley Anglia',
          type: 'interlocking-tile',
          length: 387,
          width: 204,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 100,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Marley Ludlow Major',
          type: 'interlocking-tile',
          length: 420,
          width: 295,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 100,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Sandtoft Shire Pantile',
          type: 'interlocking-tile',
          length: 380,
          width: 200,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 100,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Redland Fenland Pantile',
          type: 'interlocking-tile',
          length: 381,
          width: 200,
          eave_tile_length: 0,
          headlap: 100,
          crossbonded: 'NO',
          mingauge: 75,
          maxgauge: 100,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Tudor Traditional Handmade Clay Plain Tile',
          type: 'plain-tile',
          length: 265,
          width: 165,
          eave_tile_length: 200,
          headlap: 65,
          crossbonded: 'YES',
          mingauge: 100,
          maxgauge: 100,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Keymer Traditional Handmade Clay Plain Tile',
          type: 'plain-tile',
          length: 265,
          width: 165,
          eave_tile_length: 200,
          headlap: 65,
          crossbonded: 'YES',
          mingauge: 75,
          maxgauge: 100,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Spicer Handmade Clay Peg Tile',
          type: 'plain-tile',
          length: 255,
          width: 150,
          eave_tile_length: 190,
          headlap: 65,
          crossbonded: 'YES',
          mingauge: 95,
          maxgauge: 110,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 0,
        },
        {
          name: 'Marley Acme Single Camber',
          type: 'plain-tile',
          length: 265,
          width: 165,
          eave_tile_length: 265,
          headlap: 65,
          crossbonded: 'YES',
          mingauge: 90,
          maxgauge: 110,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 165,
        },
        {
          name: 'Wolds Clay Pantile',
          type: 'pantile',
          length: 393,
          width: 195,
          eave_tile_length: 0,
          headlap: 70,
          crossbonded: 'NO',
          mingauge: 260,
          maxgauge: 270,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 245,
        },
        {
          name: 'William Blyth Barco',
          type: 'pantile',
          length: 393,
          width: 195,
          eave_tile_length: 0,
          headlap: 70,
          crossbonded: 'NO',
          mingauge: 265,
          maxgauge: 270,
          minspacing: 1,
          maxspacing: 7,
          datasheet_link: null,
          lhTileWidth: 245,
        },
      ]);
      console.log('Tiles seeded successfully.');
    } else {
      console.log('Tiles already exist, skipping seeding.');
    }

    // Verify the database after seeding
    console.log('Verifying user table...');
    const users = await user.findAll();
    console.log('Users in database:', users.map(u => u.toJSON()));

    console.log('Verifying tile table...');
    const tiles = await tile.findAll();
    console.log('Tiles in database:', tiles.map(t => t.toJSON()));
  } catch (error) {
    console.error('Error during seeding:', error);
    throw error;
  } finally {
    await sequelize.close();
  }
};

seedDatabase().then(() => {
  console.log('Seeding completed successfully.');
}).catch((error) => {
  console.error('Seeding failed:', error);
});